#! /usr/bin/env python

import sys
import os
import re
import logging

sys.path.append(os.path.abspath(os.path.dirname(__file__),'pythonlib'))
import extargsparse

def read_file(infile=None):
    fin = sys.stdin
    if infile is not None:
        fin = open(infile,'r+b')
    rets = ''
    for l in fin:
        s = l
        if 'b' in fin.mode:
            if sys.version[0] == '3':
                s = l.decode('utf-8')
        rets += s

    if fin != sys.stdin:
        fin.close()
    logging.info('read [%s]\n%s'%(infile,rets))
    fin = None
    return rets

def set_logging(args):
    loglvl= logging.ERROR
    if args.verbose >= 3:
        loglvl = logging.DEBUG
    elif args.verbose >= 2:
        loglvl = logging.INFO
    if logging.root is not None and len(logging.root.handlers) > 0:
        logging.root.handlers = []
    logging.basicConfig(level=loglvl,format='%(asctime)s:%(filename)s:%(funcName)s:%(lineno)d\t%(message)s')
    return

def write_file(s,outfile=None):
    fout = sys.stdout
    if outfile is not None:
        fout = open(outfile, 'w+b')
    outs = s
    if 'b' in fout.mode:
        outs = s.encode('utf-8')
    fout.write(outs)
    if fout != sys.stdout:
        fout.close()
    logging.info('out %s\n%s'%(outfile,s))
    fout = None
    return 


def svcmain_handler(args,parser):
    set_logging(args)
    dname = os.path.abspath(os.path.dirname(__file__))
    config = os.path.join(dname,'config.json')
    s = read_file(config)
    sys.stdout.write('read [%s]\n%s'%(config,s))
    sys.exit(0)
    return

def outsvc_handler(args,parser):
    set_logging(args)
    ins = read_file(args.input)
    sarr = re.split('\n',ins)
    outs = ''
    bname = os.path.dirname(__file__)
    for l in sarr:
        l = l.rstrip('\r')
        l = re.sub('%SCRIPT_FILE%',__file__,l)
        l = re.sub('%SCRITP_DIR%',bname,l)
        outs += '%s\n'%(l)
    write_file(outs,args.output)
    sys.exit(0)
    return


def add_code_start(cfile,scriptn,startcode='SELFMAIN'):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '###%sEND'%(startcode)
    inserted = False
    started = False
    for l in sarr:
        l = l.rstrip('\r')
        if len(l) == 0:
            continue
        if not started and l.startswith(startnote):
            started = True
        elif started and l.startswith(endnote):
            started = False
            inserted = True
        outs += '%s\n'%(l)
    if not inserted:
        outs += '%s\n'%(startnote)
        outs += '%s start\n'%(scriptn)
        outs += '%s\n'%(endnote)
    write_file(outs,cfile)
    return True

def add_code_stop(cfile,scriptn,startcode='SELFMAIN'):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '###%sEND'%(startcode)
    inserted = False
    idx = 0
    for l in sarr:
        idx += 1
        l = l.rstrip('\r')
        if len(l) == 0:
            continue

        if idx > 1 and not inserted:
            outs += '%s\n'%(startcode)
            outs += '%s stop\n'%(scriptn)
            outs += '%s\n'%(endcode)
            inserted = True
        outs += '%s\n'%(l)
    write_file(outs,cfile)
    return True


def remove_code_start(cfile,startcode='SELFMAIN'):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '###%sEND'%(startcode)
    inserted = False
    started = False
    for l in sarr:
        l = l.rstrip('\r')
        if not started and l.startswith(startnote):
            started = True
        if not started:
            outs += '%s\n'%(l)
        if started and l.startswith(endnote):
            started = False

    write_file(outs,cfile)
    return True

def remove_code_stop(cfile,startcode='SELFMAIN'):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '###%sEND'%(startcode)
    removed = False
    started = False
    for l in sarr:
        l = l.rstrip('\r')
        if not started and l.startswith(startnote):
            started = True
        if not started:
            outs += '%s\n'%(l)
        if started and l.startswith(endnote):
            started = False
            removed = True

    write_file(outs,cfile)
    return True



def addcode_handler(args,parser):
    set_logging(args)
    bname = os.path.dirname(__file__)
    scriptn = os.path.join(bname,'selfsvc')
    add_code_start('/oem/btlunch.sh')
    add_code_stop('/oem/btstop.sh')
    sys.exit(0)
    return

def removecode_handler(args,parser):
    set_logging(args)
    bname = os.path.dirname(__file__)
    scriptn = os.path.join(bname,'selfsvc')
    remove_code_start('/oem/btlunch.sh')
    remove_code_stop('/oem/btstop.sh')
    sys.exit(0)
    return


def main():
    commandline='''
    {
        "verbose|v" : "+",
        "input|i" : null,
        "output|o" : null,
        "svcmain<svcmain_handler>##the main service#" : {
            "$" : 0
        },
        "outsvc<outsvc_handler>##to output the service##" : {
            "$" : 0
        },
        "addcode<addcode_handler>##to add start code##" : {
            "$" : 0
        },
        "removecode<removecode_handler>##to remove code ##" : {
            "$" : 0
        }
    }
    '''
    parser = extargsparse.ExtArgsParse()
    parser.load_command_line_string(commandline)
    parser.parse_command_line(None,parser)
    raise Exception('can not reach here')
    return
    return

if __name__ == '__main__':
    main()


