#! /usr/bin/env python

import sys
import os
import re
import logging

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),'pythonlib')))
import extargsparse

def read_file(infile=None):
    fin = sys.stdin
    if infile is not None:
        fin = open(infile,'r+b')
    rets = ''
    for l in fin:
        s = l
        if 'b' in fin.mode:
            if sys.version[0] == '3':
                s = l.decode('utf-8')
        rets += s

    if fin != sys.stdin:
        fin.close()
    logging.info('read [%s]\n%s'%(infile,rets))
    fin = None
    return rets

def set_logging(args):
    loglvl= logging.ERROR
    if args.verbose >= 3:
        loglvl = logging.DEBUG
    elif args.verbose >= 2:
        loglvl = logging.INFO
    if logging.root is not None and len(logging.root.handlers) > 0:
        logging.root.handlers = []
    logging.basicConfig(level=loglvl,format='%(asctime)s:%(filename)s:%(funcName)s:%(lineno)d\t%(message)s')
    return

def write_file(s,outfile=None):
    fout = sys.stdout
    if outfile is not None:
        fout = open(outfile, 'w+b')
    outs = s
    if 'b' in fout.mode:
        outs = s.encode('utf-8')
    fout.write(outs)
    if fout != sys.stdout:
        fout.close()
    logging.info('out %s\n%s'%(outfile,s))
    fout = None
    return 


def svcmain_handler(args,parser):
    set_logging(args)
    dname = os.path.abspath(os.path.dirname(__file__))
    config = os.path.join(dname,'config.json')
    s = read_file(config)
    sys.stdout.write('read [%s]\n%s'%(config,s))
    sys.exit(0)
    return

def outsvc_handler(args,parser):
    set_logging(args)
    ins = read_file(args.input)
    sarr = re.split('\n',ins)
    outs = ''
    bname = os.path.dirname(__file__)
    for l in sarr:
        l = l.rstrip('\r')
        l = l.replace('%SCRIPT_FILE%',__file__,-1)
        l = l.replace('%SCRIPT_DIR%',bname,-1)
        outs += '%s\n'%(l)
    write_file(outs,args.output)
    sys.exit(0)
    return


def _inner_add_code(cfile,lines,startcode='SELFMAIN',headed=False):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '##%sEND'%(startcode)
    inserted = False
    started = False
    idx = 0
    for l in sarr:
        idx += 1
        l = l.rstrip('\r')
        outs += '%s\n'%(l)
        if headed and not inserted:
            outs += '%s\n'%(startnote)
            outs += '%s\n'%(lines)
            outs += '%s\n'%(endnote)
            inserted = True
    if not inserted:
        outs += '%s\n'%(startnote)
        outs += '%s\n'%(lines)
        outs += '%s\n'%(endnote)
    nsarr = re.split('\n',outs)
    nouts = ''
    for l in nsarr:
        l = l.rstrip('\r')
        if len(l) == 0:
            continue
        nouts += '%s\n'%(l)
    write_file(nouts,cfile)
    return True



def main_add_code_start(cfile,scriptn,startcode='SELFMAIN'):
    return _inner_add_code(cfile,'%s start'%(scriptn),startcode,False)

def main_add_code_stop(cfile,scriptn,startcode='SELFMAIN'):
    return _inner_add_code(cfile,'%s stop'%(scriptn),startcode,True)

def _inner_remove_code(cfile,startcode='SELFMAIN'):
    s = read_file(cfile)
    sarr = re.split('\n',s)
    outs = ''
    startnote = '##%sBEGIN'%(startcode)
    endnote = '##%sEND'%(startcode)
    inserted = False
    started = False
    idx = 0
    for l in sarr:
        idx += 1
        l = l.rstrip('\r')
        if not started and l.startswith(startnote):
            logging.info('at [%d] [%s]'%(idx,l))
            started = True
        if not started:
            outs += '%s\n'%(l)
        if started and l.startswith(endnote):
            logging.info('at end [%d] [%s]'%(idx,l))
            started = False

    write_file(outs,cfile)
    return True

def main_remove_code_stop(cfile,startcode='SELFMAIN'):
    return _inner_remove_code(cfile,startcode)

def main_remove_code_start(cfile,startcode='SELFMAIN'):
    return _inner_remove_code(cfile,startcode)



def addcode_handler(args,parser):
    set_logging(args)
    bname = os.path.dirname(__file__)
    scriptn = os.path.join(bname,'selfsvc')
    main_add_code_start('/oem/btlunch.sh',scriptn)
    main_add_code_stop('/oem/btstop.sh',scriptn)
    sys.exit(0)
    return

def removecode_handler(args,parser):
    set_logging(args)
    bname = os.path.dirname(__file__)
    scriptn = os.path.join(bname,'selfsvc')
    main_remove_code_start('/oem/btlunch.sh')
    main_remove_code_stop('/oem/btstop.sh')
    sys.exit(0)
    return


def main():
    commandline='''
    {
        "verbose|v" : "+",
        "input|i" : null,
        "output|o" : null,
        "svcmain<svcmain_handler>##the main service#" : {
            "$" : 0
        },
        "outsvc<outsvc_handler>##to output the service##" : {
            "$" : 0
        },
        "addcode<addcode_handler>##to add start code##" : {
            "$" : 0
        },
        "removecode<removecode_handler>##to remove code ##" : {
            "$" : 0
        }
    }
    '''
    parser = extargsparse.ExtArgsParse()
    parser.load_command_line_string(commandline)
    parser.parse_command_line(None,parser)
    raise Exception('can not reach here')
    return
    return

if __name__ == '__main__':
    main()


